install:
  - echo "Just override default Travis CI install step to avoid automatic dependency resolution."

matrix:
  include:
  - os: linux
    sudo: required
    services:
    - docker
    script:
    - ci/build.sh
  - os: osx
    script:
    - ci/macOS.sh

deploy:
  provider: releases
  api_key:
      secure: DVGvqd0xWG0P6ELXUnE1JcXcpa12W7RcadCENLthHR7gYtYraDhNwL96mmkg8h0k7TqfvH+hyPXeVfUardETjrlUqmAYCCjsi5NPRTSoa93bqA3ZA90lwxVKr1IYQaOS0Y8vU4fGb3aKRWt2sTiCkY6bdx5nhkcX/o61PVWm6r75RTmeTqeU6WOf8CUfIlW5i34iF5IW21+oZGr8nfEI4ShCHLtCH2Jg64XfzlJ92y36oowKMoII0gvjsRY3cEimBbwNouM/0oUZeqCyO5b+gYbo+mJ+3AUAjgpth/Iod40euZUtGpwAxpJDOoyw78OWofVwsDJUEwwhh1I3+KvJBu6HDXbfxQCtvUVHNJmrwoW86Z5Dc7m7jS8G9A3USCkYr25FhZHLLPnsUvtgMp8phzKRxT562/gT1cLnCJF9NtHEzjFoJ3zkYFikQlYzgoOXL7cJtkUzl5mAA+zHtdgM0eY6CMxsyoOvFZcXDFKGV1dL5pBue9SzOzT4kI0Kn6WYrTzDnu4afSHxQSToPW/8z+GXmlliORdsj+OfjNO806ks8S6WfTH58pdRjvMh5hEjbpduLJN5OP6Bp0grvpVT7TfuqrryVloEGBc5Ul+REX8lsclPUjyhGEJjLvXcOx3KFyvQYVmEmvBukZYFss71fc9tq2Bd8RKyi3x7RY0VP8A=
  skip_cleanup: true
  file_glob: true
  file: build/build/artifacts
  on:
    tags: true

notifications:
  email: false
