install:
  - echo "Just override default Travis CI install step to avoid automatic dependency resolution."

matrix:
  include:
  - os: linux
    sudo: required
    services:
    - docker
    script:
    - ci/build.sh
  - os: osx
    script:
    - ci/macOS.sh

deploy:
  provider: releases
  api_key:
      secure: kUsJLOGhqhR7Ydw1SO/5qBemcroFCIhNJcOEuFzOHy/NlCPI2kDPloV24H8B/HtLTAdSiNqkQs5CzFxJ8wrHR0QSv9SEc3zgzSvWi6O17Kkk34X1mcCKJdBBSZb6SwU4d4XKNIJyu0FyzTsGZ9C1XT8EsNrQP5xs5F3aEEI7y/OwGZC+hs4DI7dn83b/JKnbtbcHjig2IxoiIm1la1Ru5bhN95xpreIT0V4O9KGNwbAJtPEl5SHAD+jTIvymBGoSkumjwGE3DFpmy44S+fVOjyOShlFXOcRBtUq2Kd1r7j2Vpo0Kg7EiAVyEK7LMH9RHpddedR6KXuWLuiC6iuK9FKLhaI/Ss8EWOSljZ0Lo+02gZbUofO5BHQnKvzyx9PHAIn+hfDh/mUDbedHl9BFLmN6BsMuCs1rxVubrE94UKaXgTBiUI+yVgFJ8tYkSJW+tkPgOjHFWSige96uap3qixNLVZHG7326n+EhG+7c96Mcopo+N2buA5iK4tTh7cL+a6x8qiDS2Yc/qfnGIaGQu7ix8xewl8RA3WqKL4Ac0HDk87umXi+D+pzOUAMAxpadQ5hOWOBvXKi1PR8d4i44g1HY14IX5iKnkpdAIMSK4cBKkAP6rC3Y9OGQaQv0qiT4M0lC6K/2dTMHba+/pN/k1X6Fr5zBiuh76jFDuBcpbLss=
  skip_cleanup: true
  file_glob: true
  file: build/build/artifacts
  on:
    tags: true

notifications:
  email: false
